### ISSUE TITLE
Fix race conditions when creating tables on app startup

### ISSUE THREAD

**Issue by ghost** [codelouders/schmetterling#5]
It's pain in the ass, especially when you do model changes and you just wipe database to make room for new tables schema.

Fix this please ;)

**Comment by ghost** [comment]
Just to refine this issue - the problem happens when Schetterling creates inserts admin user fixture into database. Disabling this piece of logic makes the problem go away.

**Comment by vixxx123** [comment]
schmetterling wasn't adding any user to database. You program did. I've just added postInit callback and you can put there that logic which was failing,

**Comment by ghost** [comment]
Roger that. Unfortunately this bug is still there.
