### ISSUE TITLE
File logger has Windows-specific log path hardcoded

### ISSUE THREAD

**Issue by ghost** [codelouders/schmetterling#7]
com.codelouders.shmetterling.RestExampleApp creates com.codelouders.shmetterling.rest.Rest#Rest that is being fed with new FileLogger("c:\temp\rest-container.log"). Make this configuration file wise. Don't mind that his is an example app. Log file path should be driven by configuration file.

**Comment by unkletee** [comment]
Just a test.

**Comment by vixxx123** [comment]
done by unkletee
